### PR TITLE
fixing link to Tip Sheet

### LINKED ISSUE #1878: Kraken the Code tip sheet - 404
[This tweet](https://twitter.com/whistlerlisa/status/734529897318649856) came in over the weekend.

The Kraken the Code [tip sheet](https://mozilla.github.io/mozilla-club-activity-kraken-the-code/legit-o-meter.html) isn't working. It's link is found in the 2nd paragraph under "Kraken the Code: Hunt" section.

### PR DESCRIPTION
**Pull request by hannahkane**
fixes https://github.com/mozilla/learning.mozilla.org/issues/1878

### CODE REVIEW

**Comment by hannahkane** [comment]
@soapdog - R?

**Comment by soapdog** [comment]
Merged! Thanks a lot @hannahkane

**Comment by KGorr** [comment]
Just leaving a comment here so that I'll be notified once the fix happens. I want to alert the person who caught the error once it is fixed. Thanks!

**Comment by hannahkane** [comment]
Hey @KGorr - the link to the tip sheet is fixed now!

**Comment by KGorr** [comment]
Awesome - thank you, @hannahkane and team!

**Pull request merged**
